{{- if .Values.envSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "query-exporter-helm.fullname" . }}-secretmap
  labels:
    {{- include "query-exporter-helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.envSecrets | nindent 2 }}
{{- end }}
