apiVersion: v1
kind: Service
metadata:
  name: {{ include "query-exporter-helm.fullname" . }}
  labels:
    {{- include "query-exporter-helm.labels" . | nindent 4 }}
  annotations:
    {{- include .Values.service.annotations . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "query-exporter-helm.selectorLabels" . | nindent 4 }}
